name: weather
channels:
    - conda-forge
dependencies:
    - python=3.10.6
    - numpy=1.26.4
    # MIGHT NEED THE FOLLOWING IN BASHRC
    # export NUMPY_EXPERIMENTAL_DTYPE_API=1
    - jupyter=1.0.0
    - netcdf4=1.6.4
    - xarray=2023.9.0
    - matplotlib=3.7.1
    - cartopy=0.21.1
    - wrf-python=1.3.4.1
    - sharppy=1.4.0
    - eccodes=2.31.0
    - cfgrib=0.9.11.0
    - cdsapi=0.6.1
    - anaconda:boto=2.49.0
    - ipywidgets=8.1.1
    - ipyevents=2.0.2
    - pint=0.22
    - metpy=1.6.3
    - scipy=1.11.3
    - siphon=0.9
    - vtk=9.2.6
    - pyqt=5.15.9
    - mayavi=4.8.1
    - arm_pyart=1.18.1
    - trmm_rsl=1.49
    # LINUX ONLY (comment out this line if on windows)
    # IF ON LINUX ADD
    # export RSL_PATH=/pathtouser/miniconda3/pkgs/trmm_rsl-1.49-h166bdaf_5/
    # OR SIMILAR TO BASHRC
    - gdal=3.7.0
    - wradlib=2.0.1
    - hdf5=1.14.1
    - h5py=3.9.0
    - pytest=7.4.2
    - xradar=0.5.0
    - climlab=0.8.1
    - sounderpy=3.0.3